// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCesWyGdAz6OJqc9RHQtRdXUPT_LR6oDlo',
    appId: '1:59776412564:web:ea7cd9c983498f21f3fd81',
    messagingSenderId: '59776412564',
    projectId: 'apping-28fe7',
    authDomain: 'apping-28fe7.firebaseapp.com',
    storageBucket: 'apping-28fe7.firebasestorage.app',
    measurementId: 'G-MC8KSRTBMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGnDSLfp6J2qBY50gWvHcFoLkF5ykSOgE',
    appId: '1:59776412564:android:aaa3062da8dceefbf3fd81',
    messagingSenderId: '59776412564',
    projectId: 'apping-28fe7',
    storageBucket: 'apping-28fe7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaIOvlk-Mm0RzFcSnV6pnDA8DDyEROED0',
    appId: '1:59776412564:ios:1370966ebd2b3761f3fd81',
    messagingSenderId: '59776412564',
    projectId: 'apping-28fe7',
    storageBucket: 'apping-28fe7.firebasestorage.app',
    iosBundleId: 'com.example.apping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaIOvlk-Mm0RzFcSnV6pnDA8DDyEROED0',
    appId: '1:59776412564:ios:1370966ebd2b3761f3fd81',
    messagingSenderId: '59776412564',
    projectId: 'apping-28fe7',
    storageBucket: 'apping-28fe7.firebasestorage.app',
    iosBundleId: 'com.example.apping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCesWyGdAz6OJqc9RHQtRdXUPT_LR6oDlo',
    appId: '1:59776412564:web:75d9907f5f973cd1f3fd81',
    messagingSenderId: '59776412564',
    projectId: 'apping-28fe7',
    authDomain: 'apping-28fe7.firebaseapp.com',
    storageBucket: 'apping-28fe7.firebasestorage.app',
    measurementId: 'G-030Y99CL3R',
  );
}
